local style = require "labtx-style-std"

style.macros["jan"] = "Jan."
style.macros["feb"] = "Feb."
style.macros["mar"] = "Mar."
style.macros["apr"] = "Apr."
style.macros["may"] = "May"
style.macros["jun"] = "June"
style.macros["jul"] = "July"
style.macros["aug"] = "Aug."
style.macros["sep"] = "Sept."
style.macros["oct"] = "Oct."
style.macros["nov"] = "Nov."
style.macros["dec"] = "Dec."
style.macros["acmcs"] = "ACM Comput. Surv."
style.macros["acta"] = "Acta Inf."
style.macros["cacm"] = "Commun. ACM"
style.macros["ibmjrd"] = "IBM J. Res. Dev."
style.macros["ibmsj"] = "IBM Syst.~J."
style.macros["ieeese"] = "IEEE Trans. Softw. Eng."
style.macros["ieeetc"] = "IEEE Trans. Comput."
style.macros["ieeetcad"] = "IEEE Trans. Comput.-Aided Design Integrated Circuits"
style.macros["ipl"] = "Inf. Process. Lett."
style.macros["jacm"] = "J.~ACM"
style.macros["jcss"] = "J.~Comput. Syst. Sci."
style.macros["scp"] = "Sci. Comput. Programming"
style.macros["sicomp"] = "SIAM J. Comput."
style.macros["tocs"] = "ACM Trans. Comput. Syst."
style.macros["tods"] = "ACM Trans. Database Syst."
style.macros["tog"] = "ACM Trans. Gr."
style.macros["toms"] = "ACM Trans. Math. Softw."
style.macros["toois"] = "ACM Trans. Office Inf. Syst."
style.macros["toplas"] = "ACM Trans. Prog. Lang. Syst."
style.macros["tcs"] = "Theoretical Comput. Sci."

function std_styles.formatters:nameformat(c) return "{f.~}{vv~}{ll}{, jj}" end

style.label.make = nil

return style
